### ISSUE TITLE
Neutral set?

### ISSUE THREAD

**Issue by DankMemeGuy** [d00ML0rDz/nsfw-image-urls#1]
By any chance do you have a neutral dataset? Normal pics, clothed people, etc..?

**Comment by d00ML0rDz** [comment]
Unfortunately not. If you check Kaggle, they have various datasets with a variety of different images that can be used to build a good neutral dataset e.g.

https://www.kaggle.com/datasets/hsankesara/flickr-image-dataset
https://www.kaggle.com/datasets/jigrubhatt/selfieimagedetectiondataset
https://www.kaggle.com/datasets/lijiyu/imagenet

Hope that gives you a good start :)
